-- migration: create_flashcards_schema
-- description: Initial schema for 10x Cards flashcard application
-- created: 2025-10-11
-- 
-- this migration creates the complete database schema including:
-- - enum types for flashcard status and source
-- - flashcards table for storing user flashcards with spaced repetition metadata
-- - generations table for tracking ai generation sessions
-- - generation_error_logs table for error tracking and auditing
-- - indexes optimized for common query patterns
-- - row level security (rls) policies for data isolation
-- - triggers for automatic timestamp updates
--
-- affected tables: flashcards, generations, generation_error_logs
-- special considerations: all tables use uuid primary keys and enable rls

-- ============================================================================
-- 1. create enum types
-- ============================================================================

-- flashcard_status: tracks the lifecycle state of a flashcard
-- - candidate: ai-generated flashcard awaiting user acceptance
-- - active: accepted flashcard active in the user's collection
-- - rejected: flashcard rejected by user (may be deleted)
create type flashcard_status as enum (
    'candidate',
    'active',
    'rejected'
);

-- flashcard_source: tracks the origin of the flashcard
-- - manual: flashcard created manually by user
-- - ai: flashcard generated by ai system
create type flashcard_source as enum (
    'manual',
    'ai'
);

-- ============================================================================
-- 2. create tables
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 2.1 generations table
-- ----------------------------------------------------------------------------
-- tracks each ai generation session, grouping flashcards generated together
-- stores metadata about the generation process for analytics and auditing
create table generations (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    model text not null,
    source_text_length integer not null check (source_text_length >= 1000 and source_text_length <= 10000),
    source_text_hash text not null,
    flashcards_generated integer not null default 0 check (flashcards_generated >= 0),
    created_at timestamptz not null default now()
);

-- add comment explaining the purpose of this table
comment on table generations is 'tracks ai generation sessions and groups generated flashcards';
comment on column generations.model is 'identifier of the ai model used (e.g., gpt-4o-mini)';
comment on column generations.source_text_hash is 'sha-256 hash of source text for audit purposes';
comment on column generations.flashcards_generated is 'count of flashcards generated in this session';

-- ----------------------------------------------------------------------------
-- 2.2 generation_error_logs table
-- ----------------------------------------------------------------------------
-- stores error logs from failed ai generation attempts
-- used for debugging, monitoring, and improving system reliability
create table generation_error_logs (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    error_type text not null,
    error_message text not null,
    model text not null,
    source_text_length integer not null check (source_text_length >= 0),
    source_text_hash text not null,
    created_at timestamptz not null default now()
);

-- add comments explaining error tracking
comment on table generation_error_logs is 'logs errors from ai flashcard generation for debugging and monitoring';
comment on column generation_error_logs.error_type is 'category of error (e.g., api_error, network_error, validation_error)';
comment on column generation_error_logs.source_text_hash is 'sha-256 hash of source text (protects privacy while enabling error identification)';

-- ----------------------------------------------------------------------------
-- 2.3 flashcards table
-- ----------------------------------------------------------------------------
-- main table storing all user flashcards with spaced repetition metadata
-- supports both manually created and ai-generated flashcards
create table flashcards (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    generation_id uuid null references generations(id) on delete set null,
    front text not null check (char_length(front) > 0 and char_length(front) <= 200),
    back text not null check (char_length(back) > 0 and char_length(back) <= 500),
    status flashcard_status not null default 'candidate',
    source flashcard_source not null,
    due_date timestamptz null,
    interval integer null check (interval >= 0),
    ease_factor numeric(4, 2) null check (ease_factor >= 1.3),
    repetitions integer null check (repetitions >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- add comments explaining flashcard fields
comment on table flashcards is 'stores all user flashcards with spaced repetition algorithm metadata';
comment on column flashcards.generation_id is 'links to generation session for ai-generated cards (null for manual cards)';
comment on column flashcards.front is 'front of flashcard (question/term), max 200 characters';
comment on column flashcards.back is 'back of flashcard (answer/definition), max 500 characters';
comment on column flashcards.status is 'lifecycle state: candidate (awaiting acceptance), active (in collection), rejected';
comment on column flashcards.due_date is 'next review date (null for candidate status)';
comment on column flashcards.interval is 'days until next review for spaced repetition algorithm';
comment on column flashcards.ease_factor is 'sm-2 algorithm ease factor (starting value: 2.5)';
comment on column flashcards.repetitions is 'count of consecutive successful reviews';

-- ============================================================================
-- 3. create indexes
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 3.1 indexes for flashcards table
-- ----------------------------------------------------------------------------

-- optimizes queries for user's flashcard collection sorted chronologically
-- used for: paginated collection view, recent flashcards list
create index idx_flashcards_user_created on flashcards(user_id, created_at desc);

-- partial index optimizing study session queries
-- only indexes active flashcards with scheduled reviews
-- used for: fetching flashcards due for review
create index idx_flashcards_user_due on flashcards(user_id, status, due_date) 
where status = 'active' and due_date is not null;

-- partial index for linking flashcards to their generation session
-- only indexes ai-generated flashcards (generation_id not null)
-- used for: viewing all flashcards from a specific generation
create index idx_flashcards_generation on flashcards(generation_id) 
where generation_id is not null;

-- ----------------------------------------------------------------------------
-- 3.2 indexes for generations table
-- ----------------------------------------------------------------------------

-- optimizes queries for user's generation history sorted chronologically
-- used for: generation history view, analytics
create index idx_generations_user_created on generations(user_id, created_at desc);

-- ----------------------------------------------------------------------------
-- 3.3 indexes for generation_error_logs table
-- ----------------------------------------------------------------------------

-- optimizes queries for user's error logs sorted chronologically
-- used for: error history, debugging, admin monitoring
create index idx_error_logs_user_created on generation_error_logs(user_id, created_at desc);

-- ============================================================================
-- 4. enable row level security (rls)
-- ============================================================================

-- enable rls on all tables to ensure users can only access their own data
alter table flashcards enable row level security;
alter table generations enable row level security;
alter table generation_error_logs enable row level security;

-- ============================================================================
-- 5. create rls policies for flashcards table
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 5.1 select policies for flashcards
-- ----------------------------------------------------------------------------

-- allows authenticated users to view only their own flashcards
create policy "authenticated users can view their own flashcards"
    on flashcards
    for select
    to authenticated
    using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- 5.2 insert policies for flashcards
-- ----------------------------------------------------------------------------

-- allows authenticated users to create flashcards only for themselves
-- enforces that user_id matches the authenticated user
create policy "authenticated users can insert their own flashcards"
    on flashcards
    for insert
    to authenticated
    with check (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- 5.3 update policies for flashcards
-- ----------------------------------------------------------------------------

-- allows authenticated users to update only their own flashcards
-- both using and with check ensure user cannot transfer ownership
create policy "authenticated users can update their own flashcards"
    on flashcards
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- 5.4 delete policies for flashcards
-- ----------------------------------------------------------------------------

-- allows authenticated users to delete only their own flashcards
-- supports hard delete of rejected candidates or unwanted flashcards
create policy "authenticated users can delete their own flashcards"
    on flashcards
    for delete
    to authenticated
    using (auth.uid() = user_id);

-- ============================================================================
-- 6. create rls policies for generations table
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 6.1 select policies for generations
-- ----------------------------------------------------------------------------

-- allows authenticated users to view only their own generation sessions
create policy "authenticated users can view their own generations"
    on generations
    for select
    to authenticated
    using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- 6.2 insert policies for generations
-- ----------------------------------------------------------------------------

-- allows authenticated users to create generation records only for themselves
create policy "authenticated users can insert their own generations"
    on generations
    for insert
    to authenticated
    with check (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- 6.3 update policies for generations
-- ----------------------------------------------------------------------------

-- allows authenticated users to update only their own generation records
-- useful for updating flashcards_generated count
create policy "authenticated users can update their own generations"
    on generations
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- 6.4 delete policies for generations
-- ----------------------------------------------------------------------------

-- allows authenticated users to delete their own generation records
-- note: flashcards.generation_id will be set to null due to on delete set null
create policy "authenticated users can delete their own generations"
    on generations
    for delete
    to authenticated
    using (auth.uid() = user_id);

-- ============================================================================
-- 7. create rls policies for generation_error_logs table
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 7.1 select policies for generation_error_logs
-- ----------------------------------------------------------------------------

-- allows authenticated users to view only their own error logs
-- useful for debugging and understanding generation failures
create policy "authenticated users can view their own error logs"
    on generation_error_logs
    for select
    to authenticated
    using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- 7.2 insert policies for generation_error_logs
-- ----------------------------------------------------------------------------

-- allows authenticated users to insert error logs for themselves
-- system components running as the user can log errors
create policy "authenticated users can insert their own error logs"
    on generation_error_logs
    for insert
    to authenticated
    with check (auth.uid() = user_id);

-- note: update and delete policies intentionally omitted for error logs
-- error logs should be immutable audit records
-- future admin policies may be added for log management

-- ============================================================================
-- 8. create triggers
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 8.1 trigger function for automatic updated_at timestamp
-- ----------------------------------------------------------------------------

-- creates a reusable function that updates the updated_at column
-- automatically sets updated_at to current timestamp on any row update
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

-- add comment explaining the trigger function
comment on function update_updated_at_column() is 'automatically updates updated_at column to current timestamp on row update';

-- ----------------------------------------------------------------------------
-- 8.2 apply trigger to flashcards table
-- ----------------------------------------------------------------------------

-- trigger fires before update on flashcards table
-- ensures updated_at is always current whenever a flashcard is modified
create trigger update_flashcards_updated_at
    before update on flashcards
    for each row
    execute function update_updated_at_column();

-- ============================================================================
-- migration complete
-- ============================================================================

-- this migration establishes the complete foundation for the 10x cards application
-- next steps:
-- - implement application logic for spaced repetition algorithm (sm-2 or ts-fsrs)
-- - create api endpoints for flashcard crud operations
-- - implement ai generation service
-- - add analytics queries for tracking user engagement

