-- migration: add_ai_edited_source
-- description: Adds 'ai-edited' value to flashcard_source enum to track AI-generated flashcards that were edited by users
-- created: 2025-10-12
-- 
-- this migration extends the flashcard_source enum to support three states:
-- - 'manual': flashcard created manually by user
-- - 'ai': flashcard generated by AI (unmodified)
-- - 'ai-edited': flashcard generated by AI and edited by user
--
-- context: with the new server-side generation flow, flashcards are saved immediately
-- after generation and can be edited before activation. we need to track which
-- AI-generated flashcards have been modified by users for analytics and metrics.
--
-- affected types: flashcard_source
-- special considerations: ALTER TYPE ... ADD VALUE cannot run inside a transaction block
--                        in some PostgreSQL versions, but supabase migrations handle this

-- ============================================================================
-- 1. add new value to flashcard_source enum
-- ============================================================================

-- add 'ai-edited' value to the flashcard_source enum
-- this allows tracking flashcards that were generated by AI but modified by users
-- order matters: new value will be added after existing values
alter type flashcard_source add value 'ai-edited';

-- ============================================================================
-- migration complete
-- ============================================================================

-- the flashcard_source enum now supports:
-- - 'manual': user-created flashcards
-- - 'ai': AI-generated flashcards (unmodified)
-- - 'ai-edited': AI-generated flashcards that were edited by users
--
-- this enables tracking for the success metric:
-- "75% of flashcards in collection come from AI generation"
-- where we count source='ai' OR source='ai-edited' as AI-generated

